/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jsonfile.db.browser;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author KorzinowskiAndreasMI
 */
public class BrowserView extends javax.swing.JFrame implements Observer {

    BrowserController control;
    
    /**
     * Creates new form BrowserView
     */
    public BrowserView(BrowserController c) {
        control = c;
        initComponents();
        
        this.mi_beenden.addActionListener(control);
        this.mi_beenden.setActionCommand(BrowserStatics.APP_END);
        
        
    }

//    BrowserView(BrowserController aThis) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jSplitPane2 = new javax.swing.JSplitPane();
        scrollpanelList = new javax.swing.JScrollPane();
        scrollpanelDetail = new javax.swing.JScrollPane();
        scrollpannelFile = new javax.swing.JScrollPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mi_beenden = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setMinimumSize(new java.awt.Dimension(247, 100));

        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        scrollpanelList.setMinimumSize(new java.awt.Dimension(100, 100));
        jSplitPane2.setTopComponent(scrollpanelList);

        scrollpanelDetail.setMinimumSize(new java.awt.Dimension(100, 100));
        jSplitPane2.setRightComponent(scrollpanelDetail);

        jSplitPane1.setRightComponent(jSplitPane2);

        scrollpannelFile.setMinimumSize(new java.awt.Dimension(100, 100));
        jSplitPane1.setLeftComponent(scrollpannelFile);

        jMenu1.setText("Datei");

        mi_beenden.setText("Beenden ...");
        jMenu1.add(mi_beenden);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Bearbeiten");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JMenuItem mi_beenden;
    private javax.swing.JScrollPane scrollpanelDetail;
    private javax.swing.JScrollPane scrollpanelList;
    private javax.swing.JScrollPane scrollpannelFile;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object o1) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
